In [1]:
%load_ext lab_black

import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm
from scipy import stats

In [2]:
data_2021 = pd.read_csv("../data/airbnb_listings_2021.csv")
data_2021.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365', 'number_of_reviews_ltm', 'license'],
      dtype='object')

In [ ]:
# Dropping irrelevant columns
datan = data_2021[
    [
        "price",
        "neighbourhood",
    ]
]
datan.dropna()
datan = pd.get_dummies(datan, columns=["neighbourhood"])
datan.drop(["neighbourhood_Midtown"], axis=1, inplace=True)
datan.astype(float)
datan

In [ ]:
# Dropping irrelevant columns
datang = data_2021[
    [
        "price",
        "neighbourhood_group",
    ]
]
datang.dropna()
datang = pd.get_dummies(datang, columns=["neighbourhood_group"])
datang.drop(["neighbourhood_group_Bronx"], axis=1, inplace=True)
datang.astype(float)
datang

In [ ]:
Y = datan["price"]
Y

In [ ]:
X1 = datan
datan.drop(["price"], axis=1, inplace=True)
X1c = sm.add_constant(X1)
X1c

In [ ]:
X2 = datang
datang.drop(["price"], axis=1, inplace=True)
X2c = sm.add_constant(X2)
X2c

In [ ]:
esta = sm.OLS(Y, X1c)
est2 = esta.fit()
est2.summary()

In [ ]:
estb = sm.OLS(Y, X2c)
est2 = estb.fit()
est2.summary()

In [3]:
# Dropping irrelevant columns
datax = data_2021[
    [
        "price",
        "neighbourhood",
    ]
]
datax.dropna()
datax = pd.get_dummies(datax, columns=["neighbourhood"])

# datax.drop(["neighbourhood_group_Bronx"], axis=1, inplace=True)
datax.astype(float)

,price,neighbourhood_Allerton,neighbourhood_Arden Heights,neighbourhood_Arrochar,neighbourhood_Arverne,neighbourhood_Astoria,neighbourhood_Bath Beach,neighbourhood_Battery Park City,neighbourhood_Bay Ridge,neighbourhood_Bay Terrace,...,neighbourhood_Westchester Square,neighbourhood_Westerleigh,neighbourhood_Whitestone,neighbourhood_Williamsbridge,neighbourhood_Williamsburg,neighbourhood_Willowbrook,neighbourhood_Windsor Terrace,neighbourhood_Woodhaven,neighbourhood_Woodlawn,neighbourhood_Woodside
0,150.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,76.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,60.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,275.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,68.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36918,86.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36919,71.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36920,85.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36921,66.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36922,114.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
s = datax.sum()
s

price                            6246855
neighbourhood_Allerton                32
neighbourhood_Arden Heights            4
neighbourhood_Arrochar                18
neighbourhood_Arverne                 85
                                  ...
neighbourhood_Willowbrook              1
neighbourhood_Windsor Terrace        106
neighbourhood_Woodhaven               60
neighbourhood_Woodlawn                 7
neighbourhood_Woodside               386
Length: 224, dtype: int64